apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-config-scanner.fullname" . }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kube-config-scanner.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "kube-config-scanner.fullname" . }}
    spec:
      serviceAccountName: {{ include "kube-config-scanner.fullname" . }}-serviceaccount
      containers:
          - name: {{ include "kube-config-scanner.fullname" . }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            ports:
              - containerPort: 8080
            env:
              - name: MONGO_URI
                valueFrom:
                  secretKeyRef:
                    name: mongodb-secret
                    key: MONGO_URI
              - name: MONGO_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: mongodb-secret
                    key: MONGO_DATABASE
              - name: CLUSTER_NAME
                value: {{ .Values.clusterName | quote }}
            volumeMounts:
              - name: temp-storage
                mountPath: /tmp/kube-config-scanner
              - name: logs-storage
                mountPath: /kube-config-scanner/logs
      volumes:
        - name: temp-storage
          emptyDir:
            sizeLimit: "200Mi"
        - name: logs-storage
          persistentVolumeClaim:
            claimName: {{ include "kube-config-scanner.fullname" . }}-pvc
