apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mongo-init-script
data:
  mongo-init.sh: |
    set -e

    mongosh -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD <<EOF
    use $MONGO_INITDB_DATABASE

    db.log.insertOne({"message": "Database created."});
    db.createUser({
      user: '$MONGO_INITDB_ROOT_USERNAME',
      pwd: '$MONGO_INITDB_ROOT_PASSWORD',
      roles: ["readWrite", "dbAdmin"]
    });
    EOF
