apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MONGO_URI: {{ .Values.mongodb.uri | b64enc }}
  MONGO_DATABASE: {{ .Values.mongodb.database | b64enc }}
