apiVersion: batch/v1
kind: Job
metadata:
  name: trivy-scan-job
spec:
  template:
    metadata:
      name: trivy-scan
    spec:
      containers:
        - name: trivy
          image: aquasec/trivy:0.43.1
          command: [ "sh", "-c" ]
          args:
            - >
              trivy k8s --format json --timeout 3600s --all-namespaces -q --scanners "config,secret" --severity "HIGH,CRITICAL" all
      restartPolicy: Never
