logging:
  level:
    'io.kubernetes': TRACE

environment:
  in-cluster: true

filesystem:
  locations:
    yaml: /tmp/kube-config-scanner/yaml
    score: /tmp/kube-config-scanner/score
    hunter: /tmp/kube-config-scanner/hunter
    bench: /tmp/kube-config-scanner/bench
