kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-config-scanner-clusterrole
  namespace: kube-config-scanner
rules:
  - apiGroups: [""]
    resources: [pods, nodes]
    verbs: [get, watch, list]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "watch", "list", "create", "delete"]