apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-config-scanner-pvc
  namespace: kube-config-scanner
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
